"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, BriefcaseBusiness, ChevronRight, Compass, ExternalLink, MessageCircleQuestion, Package, Sparkles } from "lucide-react";
import { QUICK_NAV_SERVICES, QUICK_NAV_PRODUCTS, QUICK_NAV_EXPLORE, type QuickNavItem } from "@/lib/navigation";
import { NAV_ICON_MAP } from "@/lib/nav-icons";
import { cn } from "@/lib/utils";

type Group = "services" | "products" | "explore";
type MegaMenuProps = { activeGroup: Group; navigation?: { services: QuickNavItem[]; products: QuickNavItem[]; explore: QuickNavItem[] } };

const groupCopy: Record<Group, { label:string; title:string; description:string }> = {
  services: { label:"Layanan", title:"Jasa desain & branding", description:"Pilih layanan sesuai tahap bisnis Anda — dari identitas visual sampai materi promosi." },
  products: { label:"Produk", title:"Katalog cetak & advertising", description:"Temukan produk berdasarkan kebutuhan, lalu lanjut ke detail, spesifikasi, kalkulator, dan pemesanan." },
  explore: { label:"Eksplor", title:"Insight, portfolio & company", description:"Kenali karya, artikel, FAQ, dan informasi Madina Solution tanpa mencampur isi katalog." },
};

function Icon({ item }: { item: QuickNavItem }) { const I = NAV_ICON_MAP[item.icon]; return <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-dark-50 text-dark-600 transition-colors group-hover:bg-primary group-hover:text-white"><I className="h-4 w-4" /></span>; }

export function MegaMenu({ activeGroup, navigation = { services: QUICK_NAV_SERVICES, products: QUICK_NAV_PRODUCTS, explore: QUICK_NAV_EXPLORE } }: MegaMenuProps) {
  const copy = groupCopy[activeGroup];
  const items = navigation[activeGroup];
  return <div className="absolute left-1/2 top-full z-50 w-[min(1040px,calc(100vw-2rem))] -translate-x-1/2 pt-3">
    <div className="overflow-hidden rounded-[28px] border border-dark-200 bg-white shadow-[0_28px_80px_-30px_rgba(15,23,42,.35)] ring-1 ring-black/5">
      {activeGroup === "services" && <div className="grid grid-cols-[1fr_1.7fr]"><div className="border-r border-dark-100 bg-gradient-to-br from-primary-50 via-white to-white p-7"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary text-white"><BriefcaseBusiness className="h-5 w-5"/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.2em] text-primary">{copy.label}</p><h3 className="mt-1 text-2xl font-black tracking-tight text-dark-900">{copy.title}</h3><p className="mt-3 text-sm leading-6 text-dark-500">{copy.description}</p><Link href="/services" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-dark-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-dark-800">Semua layanan <ArrowRight className="h-4 w-4"/></Link></div><div className="p-6"><div className="grid grid-cols-2 gap-2">{items.map(i=><Link key={i.href} href={i.href} className="group flex gap-3 rounded-2xl border border-dark-100 p-3 hover:border-primary-200 hover:bg-primary-50/60 focus:outline-none focus:ring-2 focus:ring-primary/25"><Icon item={i}/><span className="min-w-0"><span className="block text-sm font-bold text-dark-800 group-hover:text-primary">{i.name}</span>{i.description&&<span className="mt-1 block text-xs leading-5 text-dark-400">{i.description}</span>}</span><ChevronRight className="mt-1 h-4 w-4 shrink-0 text-dark-300 group-hover:text-primary"/></Link>)}</div></div></div>}
      {activeGroup === "products" && <div className="grid grid-cols-[1.7fr_1fr]"><div className="p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">{copy.label}</p><h3 className="mt-1 text-2xl font-black tracking-tight text-dark-900">{copy.title}</h3><p className="mt-2 text-sm leading-6 text-dark-500">{copy.description}</p></div><Link href="/products" className="mt-1 inline-flex shrink-0 items-center gap-1 text-xs font-bold text-dark-500 hover:text-primary">Katalog penuh <ExternalLink className="h-3.5 w-3.5"/></Link></div><div className="mt-6 grid grid-cols-2 gap-2">{items.map(i=><Link key={i.href} href={i.href} className="group flex items-center gap-3 rounded-2xl border border-dark-100 p-3 hover:border-primary-200 hover:bg-primary-50/60 focus:outline-none focus:ring-2 focus:ring-primary/25"><Icon item={i}/><span className="truncate text-sm font-bold text-dark-700 group-hover:text-primary">{i.name}</span></Link>)}</div></div><aside className="bg-dark-950 p-7 text-white"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><Package className="h-5 w-5"/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.2em] text-primary-300">Custom</p><h3 className="mt-1 text-xl font-black">Produk sesuai brief Anda</h3><p className="mt-3 text-sm leading-6 text-white/65">Kirim kebutuhan ukuran, bahan, finishing, kuantitas, dan desain. Tim akan membantu menentukan konfigurasi.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-dark">Konsultasi <ArrowRight className="h-4 w-4"/></Link></aside></div>}
      {activeGroup === "explore" && <div className="grid grid-cols-[1fr_1fr]"><div className="bg-dark-50/80 p-7"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Compass className="h-5 w-5"/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.2em] text-primary">{copy.label}</p><h3 className="mt-1 text-2xl font-black tracking-tight text-dark-900">{copy.title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-dark-500">{copy.description}</p><div className="mt-6 grid gap-2">{items.map(i=><Link key={i.href} href={i.href} className="group flex items-center gap-3 rounded-2xl bg-white p-3 shadow-sm ring-1 ring-dark-100 hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-primary/25"><Icon item={i}/><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-dark-800 group-hover:text-primary">{i.name}</span>{i.description&&<span className="block text-xs text-dark-400">{i.description}</span>}</span><ChevronRight className="h-4 w-4 text-dark-300 group-hover:text-primary"/></Link>)}</div></div><div className="p-7"><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">Editorial</p><h3 className="mt-1 text-xl font-black text-dark-900">Temukan lebih banyak</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/blog" className="rounded-2xl border border-dark-100 p-4 hover:border-primary-200 hover:bg-primary-50"><BookOpen className="h-5 w-5 text-primary"/><span className="mt-4 block text-sm font-bold text-dark-800">Insight & Artikel</span><span className="mt-1 block text-xs leading-5 text-dark-400">Panduan desain, printing, branding, dan bisnis.</span></Link><Link href="/portfolio" className="rounded-2xl border border-dark-100 p-4 hover:border-primary-200 hover:bg-primary-50"><Sparkles className="h-5 w-5 text-primary"/><span className="mt-4 block text-sm font-bold text-dark-800">Portfolio</span><span className="mt-1 block text-xs leading-5 text-dark-400">Karya dan studi kasus pilihan.</span></Link></div><Link href="/contact" className="mt-4 flex items-center justify-between rounded-2xl bg-primary p-4 text-white hover:bg-primary-dark"><span className="flex items-center gap-2"><MessageCircleQuestion className="h-5 w-5"/><span><span className="block text-sm font-bold">Butuh bantuan?</span><span className="block text-xs text-white/75">Mulai konsultasi</span></span></span><ArrowRight className="h-4 w-4"/></Link></div></div>}
    </div>
  </div>;
}
